### PR TITLE
Added auto-update, global user settings and some QoL stuff

### PR DESCRIPTION
**Pull request by Eruyome**

### CODE REVIEW

**Comment by Eruyome** [comment]
Those conflicting files have to be removed.

Anyway, you don't have to merge it yet but I implemented all changes done over at TradeMacro. And again, some testing wouldn't hurt but my quick tests were successful. Will test in more detail when I consider this done (waiting for beta feeback).

**Comment by Eruyome** [comment]
@aRTy42 I believe the user settings/updater stuff is release ready. I also started adding parsing for league stones and relics, but for relics I only know that Chris wants to make sure to expose the `is_relic` flag to the ctrl+c information so I'm not sure yet how to parse them.

**Comment by aRTy42** [comment]
Ok, I'll look at it later. I guess with relics we either just wait for the league or we ask GGG a few days before league start how they decided to implement it.

**Comment by Eruyome** [comment]
Well, Chris could have been a bit more specific in his answer to my email. He just mentioned the is_relic flag, so I'm assuming they have the rarity `unique` with some additional flag.

**Comment by Eruyome** [comment]
I'll leave this here for testing purposes. Just guessing for now how this looks.

```
Rarity: Magic
Plentiful Breach Leaguestone of Swarming
--------
Consumes 1 of 3 Charges on Use
Currently has 2 Charges
--------
Item Level: 75
--------
Next Area will Contain a Breach
--------
Breaches in the Area will have 18% increased Monster density
Next Area will COntain 2 additional Breaches
--------
Corrupted
```

```
Rarity: Normal
Ancient Reliquary Key
--------
Item Level: 78
--------
It is time for the Goddess to give her final verdict.
Your fate rests in her even hands.
--------
Travel to the Aspirant's Plaza by using this item in the Eternal Laboratory or a personal Map Device. Can only be used once. You must have completed the six different Trials of Ascendancy found in Maps in order to access this area.
```

**Comment by Eruyome** [comment]
Double implicits are also not supported, will take a look at it.

```
Rarity: Magic
Chalybeous Greatwolf Talisman
--------
Requirements:
Level: 48
--------
Item Level: 75
--------
Talisman Tier: 4
--------
10% increased maximum Life
9% increased Quantity of Items found
--------
+57 to maximum Mana
--------
The wolf greeted the king,
In the light of the harvest moon.
The wolf offered the strength of the wild,
And the king paid for it in blood.
--------
Corrupted
```

**Comment by Eruyome** [comment]
We should filter a few pseudo mods. Example:
- No `Fire Damage with Weapons` since there's no `Weapon Elemental Damage`.
- No `Fire Spell Damage` since there's no `Spell Damage`.
- Only `Fire/Cold/Lightning Damage` since there's `Elemental Damage`.


```
Rarity: Rare
Damnation Nail
Opal Ring
--------
Requirements:
Level: 80
--------
Item Level: 80
--------
25% increased Elemental Damage
--------
Adds 7 to 11 Physical Damage to Attacks
26% increased Cold Damage
+67 to maximum Life
+8% to Fire Resistance
+9% to all Elemental Resistances
```

toomanymods

This should really be done, not sure I want to touch that code right now though.
@aRTy42 you don't happen to want to take a look at that? ;-)

**Comment by Eruyome** [comment]
Added parsing charges (current, max, usage) of flasks and leaguestones. Flasks don't show their affixes on the tooltip but the affix count. Leaguestones show neither. I'm not familiar with the code and didn't find where to fix this (without looking too much).

**Comment by Eruyome** [comment]
Oh and you should start writing patch notes, your's are way more detailed then mine^^

**Comment by aRTy42** [comment]
What's the current situation with Win10 issues and errors regarding the json functions? I've seen that the last problem reported in your TradeMacro thread from pR1sm was solved with the latest TradeMacro release.

Should ItemInfo also get a fallback.exe or a startup variant that only runs the bare minimum (for people that have issues with the updater or winhttp etc.) or is the current state expected to work fine for everyone?

**Comment by Eruyome** [comment]
Most reported problems were caused by running the wrong scripts or the fallback exe which had some variables missing because the merge scripts are passing them to the main scripts (which isn't happening for the exe, that's fixed). The fallback exe was only intended for users having "Error: Call to nonexistent function" issues, 1 or 2 people mentioned that it helped them, but in the end I have no idea if it really solves anything. ItemInfos update already has the UrlDownloadToFile fallback working, this should only fail if Internet Explorer is not installed or some firewall is blocking it, that's very unlikely.

Should it fail nonetheless, disabling the update via settings will work, too. I can make sure that the script won't fail because of this and simply runs without being able to update.

**Pull request merged**
