### PR TITLE
Added global variable for settingsUI-width

### PR DESCRIPTION
**Pull request by Eruyome**
Requesting this change to help me with our TradeMacro. I'd like to add some settings to PoE-ItemInfos Settings UI and need to change the window width to manage that. By using a global variable for the width I can overwrite the window dimensions without touching ItemInfos code.

### CODE REVIEW

**Comment by aRTy42** [comment]
Is the width enough? If we introduce variables at that point, we can also use one for the height, if that might be useful.

**Comment by Eruyome** [comment]
Don't think I need the height, but sure, why not. Window title (also for the menu entry in the context menu) wouldn't hurt either. 

Quick question, the icon was always white as far as i can remember, now it's turquoise (or something like that), is this intended?

**Comment by aRTy42** [comment]
I don't see any change with the icon, it is still white for me.

**Comment by Eruyome** [comment]
It seems you're right, but somehow the one we have in our forked PoE-ItemInfo is not white, that's odd.

**Pull request merged**
