### PR TITLE
added nodeJS script to create a release archive to attach on github

### PR DESCRIPTION
**Pull request by Eruyome**

### CODE REVIEW

**Comment by Eruyome** [comment]
Made a "little" nodeJS script to create an archive (zip) to attach to github releases.

- The repository and urls are read from `.git/config` folder/file.
- Script compares local version number with latest published version number to make sure the local one is higher.
- Script downloads the `master.zip`from the master branch, extracts it, deletes some file (`.gitignore` for example) and creates a new `.zip` with the version number in the file name.  
- Should have all the error-handling/fallbacks one could need.

Running this is easy, simply open a console/terminal in `lib/` folder and run `npm start`. 

script

**Comment by aRTy42** [comment]
"Published version is higher than the local version"

Nope.

**Comment by Eruyome** [comment]
Well, it's doing the right things but I made a mistake in my console.log...

**Comment by aRTy42** [comment]
The main purpose is to get rid of the two .git... files and the .markdown, correct?

**Comment by Eruyome** [comment]
Well, more or less, I just liked the idea of having a fancy script to prepare the zip-file to attach to the github releases :p 
Also, I sometimes forget to change the version number before making a release, that should solve this problem, too. Would be even better to check the version again after downloading the master.zip with the file included there.

**Pull request merged**
