### PR TITLE
 added tray menu to show update notes; added function setAfkMessage to addtional macros

### PR DESCRIPTION
**Pull request by Eruyome**
Again, other scripts can hook into this by adding to a file list.

### CODE REVIEW

**Comment by Eruyome** [comment]
I'm pretty sure I'm not reverting any of your changes (mapMatchlist etc) but please make sure.

**Comment by Eruyome** [comment]
Btw there's still a pull request ;-)

**Comment by aRTy42** [comment]
I'm aware. I wanted to leave it open until I put out the next release because initially you added commits quite often.

**Comment by Eruyome** [comment]
That's true, if I don't add anything for a few days you should be save though^^
Aside from that I like to use pull request like branches, from time to time you should just merge them to master and make a new one ;-)

**Pull request merged**
